model: convnext_base_384_in22ft1k
batch_size: 4
image_size: 512
seed: 42
pretrained: true
num_workers: 15
pin_memory: true
train_dir: /content/images/
train_file_path: /content/train.csv
epochs: 15
in_channels: 3
folds:
  - 0
  - 1
  - 2
  - 3
  - 4
scheduler_name: CosineAnnealingWarmRestarts
optimizer: Adam
T_0: 5
T_max: 5
T_mult: 1
min_lr: 1e-8
max_lr: 1e-3
weight_decay: 1e-6
target_size: 3
device: cuda
model_dir: convnext_base_384_in22ft1k_mixup_rgbonly_512_image_size
n_fold: 5
mixup: True
mixup_alpha : 1.0
optimizer_args:
  lr: 1.0E-5

