model: convnext_tiny_384_in22ft1k
batch_size: 8
image_size: 512
seed: 42
pretrained: true
num_workers: 15
pin_memory: true
train_dir: /home/mithil/PycharmProjects/Rice/data/images/
train_file_path: /home/mithil/PycharmProjects/Rice/data/train.csv
epochs: 15
in_channels: 3
folds:
  - 0
  - 1
  - 2
  - 3
  - 4
scheduler_name: CosineAnnealingWarmRestarts
optimizer: Adam
T_0: 5
T_max: 5
T_mult: 1
min_lr: 1e-7
max_lr: 1e-3
weight_decay: 1e-6
target_size: 3
device: cuda
model_dir: /home/mithil/PycharmProjects/Rice/models/convnext_tiny_384_in22ft1k_mixup_rgbonly
n_fold: 5
mixup: True
mixup_alpha : 1.0
optimizer_args:
  lr: 4.0E-5

