model: swinv2_base_window12to24_192to384_22kft1k
batch_size: 16
image_size: 384
seed: 42
pretrained: false
num_workers: 4
pin_memory: true
test_dir: /home/mithil/PycharmProjects/Rice/data/images/
test_file: /home/mithil/PycharmProjects/Rice/data/test.csv
model_path: /home/mithil/PycharmProjects/Rice/models/log_loss/swinv2_base_window12to24_192to384_22kft1k_25_epoch_delayed_mixup
probablity_file: /home/mithil/PycharmProjects/Rice/submission/swinv2_base_window12to24_192to384_22kft1k_25_epoch_delayed_mixup_tta.npy
submission_file: /home/mithil/PycharmProjects/Rice/submission/swinv2_base_window12to24_192to384_22kft1k_25_epoch_delayed_mixup_tta.csv
in_channels: 3
target_size: 3
device: cuda