model: convnext_large_384_in22ft1k
batch_size: 8
image_size: 512
seed: 42
pretrained: false
num_workers: 4
pin_memory: true
test_dir: /home/mithil/PycharmProjects/Rice/data/images/
test_file: /home/mithil/PycharmProjects/Rice/data/test.csv
model_path: /home/mithil/PycharmProjects/Rice/models/log_loss/convnext_large_384_in22ft1k_25_epoch
probablity_file: /home/mithil/PycharmProjects/Rice/submission/convnext_large_384_in22ft1k_25_epoch_tta.npy
submission_file: /home/mithil/PycharmProjects/Rice/submission/convnext_large_384_in22ft1k_25_epoch_tta.csv
in_channels: 3
target_size: 3
device: cuda