model: swinv2_large_window12to24_192to384_22kft1k
batch_size: 4
image_size: 384
seed: 42
pretrained: false
num_workers: 8
pin_memory: true
test_dir: /home/mithil/PycharmProjects/Rice/data/images/
test_file: /home/mithil/PycharmProjects/Rice/data/test.csv
model_path: /home/mithil/PycharmProjects/Rice/models/log_loss/swinv2_large_window12to24_192to384_22kft1k_pseudo_25_epoch_diff_type
probablity_file: /home/mithil/PycharmProjects/Rice/submission/swinv2_large_window12to24_192to384_22kft1k_pseudo_25_epoch_diff_type_tta.npy
submission_file: /home/mithil/PycharmProjects/Rice/submission/swinv2_large_window12to24_192to384_22kft1k_pseudo_25_epoch_diff_type_tta  .csv
in_channels: 3
target_size: 3
device: cuda