model: convnext_small_384_in22ft1k
batch_size: 16
image_size: 384
seed: 42
pretrained: true
num_workers: 4
pin_memory: true
test_dir: /home/mithil/PycharmProjects/Rice/data/images/
test_file: /home/mithil/PycharmProjects/Rice/data/test.csv
model_path: /home/mithil/PycharmProjects/Rice/models/log_loss/convnext_small_384_image_size
probablity_file: /home/mithil/PycharmProjects/Rice/submission/convnext_small_384_image_size.npy
submission_file: /home/mithil/PycharmProjects/Rice/submission/convnext_small_384_image_size.csv
in_channels: 3
target_size: 3
device: cuda