model: convnext_small_384_in22ft1k
batch_size: 16
image_size: 512
seed: 42
pretrained: false
num_workers: 3

pin_memory: true

train_dir: /home/mithil/PycharmProjects/Rice/data/images
train_file_path: /home/mithil/PycharmProjects/Rice/data/train.csv
in_channels: 3

target_size: 3
device: cuda
model_dir: /home/mithil/PycharmProjects/Rice/models/fix_csv_models/convnext_small_512_no_aug
n_fold: 5
oof_file_path: /home/mithil/PycharmProjects/Rice/oof/convnext_small_512_no_aug_oof.csv
oof_probablity_path: /home/mithil/PycharmProjects/Rice/oof/convnext_small_512_no_aug_oof.npy
folds:
  - 0
  - 1
  - 2
  - 3
  - 4