convnext_small_384_no_aug:
  cv: 0.097219
  lb: 0.131418
  cfg:
    model: convnext_small_384_in22ft1k
    batch_size: 8
    image_size: 384
    seed: 42
    pretrained: true
    epochs: 15
    in_channels: 3
    folds:
      - 0
      - 1
      - 2
      - 3
      - 4
    scheduler_name: CosineAnnealingWarmRestarts
    optimizer: Adam
    T_0: 5
    T_max: 5
    T_mult: 1
    min_lr: 1e-7
    max_lr: 1e-3
    weight_decay: 1e-6
    target_size: 3
    n_fold: 5
    optimizer_args:
      lr: 1.0E-5
  notes: "Baseline Model , nothing special"
  Augs:
    A.RandomResizedCrop(height=DIM, width=DIM),
    A.HorizontalFlip(),
    A.VerticalFlip(),
  model_dir: "/home/mithil/PycharmProjects/Rice/models/log_loss/convnext_small_384_image_size"
  files:
    inference_file: /home/mithil/PycharmProjects/Rice/submission/convnext_small_384_image_size.csv
    oof_file: /home/mithil/PycharmProjects/Rice/oof/convnext_small_384_image_size_oof.csv


